// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"giter/controllers"
	"giter/repositories"
	"giter/services"
)

// Injectors from wire.go:

func InitializeRouter() controllers.IRequestController {
	iRequestRepository := repositories.NewRequestRepository()
	iRequestService := services.NewRequestService(iRequestRepository)
	iRequestController := controllers.NewRequestController(iRequestService)
	return iRequestController
}
